name: Node.js Package

on:
  workflow_dispatch:
  push:
    branches:
      - node-support

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
          check-latest: true
          registry-url: https://npm.pkg.github.com/
          scope: '@erosendo'
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}